project:
  type: website
  output-dir: docs

website:
  title: "Natalie Smith"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      # - href: contact.qmd
      #   text: Contact
        

format:
  html:
    theme: Lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual
